### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by praveenbehara** [watson-developer-cloud/conversation-connector#20]
On Windows 7 x64, when running the ./setup.sh -s command, a couple of issues happened.
1. Where to run a shell script on Windows??
Installed GIT and used the Git Bash window.
2. Segmentation Fault
After running the setup.sh, getting following error
$ ./setup.sh -s
Checking for CF login credentials...
Syncing wsk namespace with CF namespace...
Checking for or creating cloudant instance...
Creating deployment pipeline(s)...
./setup.sh: line 158: 10448 Segmentation fault      jq -r '.pipeline[]' ${PROVIDERS_FILE} &> /dev/null
ERROR: Providers/credentials file missing pipeline JSON key.

The problem is the redirection.. remove "&> /dev/null" and it will work well.

**Comment by dgterry** [comment]
Hello,
It sounds like you are doing a Facebook based deployment? Guessing based on the mention of setup.sh -s. For Windows we recommend the automated deploy: https://github.com/watson-developer-cloud/conversation-connector/tree/master/channels/facebook#automated-deployment due to some of the reasons you mentioned.  For what it is worth I do run the scripts in Git Bash's mingw64 shell. It sounds like you figured that out, is your solution working for you or might you be able to try the automated approach?

**Comment by dgterry** [comment]
going to close this as I believe there are workarounds, using a shell emulator as you mentioned with some tweaks to the script, as well as an automated solution.  If neither is working for you please let us know.
