### ISSUE TITLE
Slack deploy does not store bot_users to Cloudant anymore

### ISSUE THREAD

**Issue by data-henrik** [watson-developer-cloud/conversation-connector#66]
I was contacted because the tutorial https://console.bluemix.net/docs/tutorials/slack-chatbot-database-watson.html#build-a-database-driven-slackbot does not work anymore.
After debugging, we found out that the part "bot_users" along with access token and bot access token are not stored in the authdb document.

After manually creating such a snippet and patching the doc in Cloudant, it worked again.

This is what we added:

```
      "WxxIDfromError": {
        "access_token": "xoxp-183775443795-111118049-1111110041348-bd913d9618",
        "bot_access_token": "xoxb-1837111111-11111-1111OwG"
      }
    }
```

**Comment by vickyni** [comment]
I followed the steps on https://console.stage1.bluemix.net/docs/tutorials/slack-chatbot-database-watson.html#build-a-database-driven-slackbot to build slack bot for test first, but there was no response.
Then come to the author of this tutorial for help. With Henrik's help, we checked step by step for several times, finally we found that was due to the bot user info missing. We fixed this issue manually for temp by adding the needed info. But the final solution should be fix that bug.
Thanks Henrik. Thanks team!
