### ISSUE TITLE
error: Unable to create action '...': The requested resource does not exist. (code ...)

### ISSUE THREAD

**Issue by aFelipeSP** [watson-developer-cloud/conversation-connector#72]
At the end of setup.sh execution I got the following errors:

Your Request URL is: https://openwhisk.ng.bluemix.net/api/v1/web/xxxxxxxxxxxxx_dev/xxxxxxxxxxxxxxxx_facebook/receive.text
error: Unable to create action 'xxxxxxxxxxxxx_postsequence': The requested resource does not exist. (code xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx)
Run 'wsk --help' for usage.
error: Unable to create action 'xxxxxxxxxxxxxxx': The requested resource does not exist. (code xxxxxxxxxxxxxxxxxxxxxxxxxx)
Run 'wsk --help' for usage.
Done.

I tried also to enter https://console.ng.bluemix.net/openwhisk/editor but this url does not exist and that's where I do step 21 of Messenger tutorial.

**Comment by dgterry** [comment]
The current URL should be https://console.bluemix.net/openwhisk/actions
from there you'll want to find <pipeline_name>_facebook/receive and click on it. In the page that loads up click endpoints in the left hand frame.  @rrberry maybe we can update the instructions since the UI has changed? 

@aFelipeSP as to the script error could you paste the complete output of the script (or at least the part where it starts trying to create the database and actions) usually an earlier failure leads to the one you listed. It's fine if you want to xxx out any sensitive data.

**Comment by aFelipeSP** [comment]
I tried one more time to run the setup.sh and got the same error ¿have anyone experienced this, or does anyone have an idea how to solve it?
