### ISSUE TITLE
An error occurred while deploying components to IBM Cloud Functions. For troubleshooting information, see https://github.com/watson-developer-cloud/conversation-connector/blob/master/README.md#troubleshooting.

### ISSUE THREAD

**Issue by DancingCryptos** [watson-developer-cloud/conversation-connector#76]
I consistently receive the following message when I try to deploy:

Can someone help me with what's missing? I'm trying to deploy with the Watson's "Deploy to Slack" option.  Workspace ID:  9e4860f9-df30-4bd6-b918-cd7422cd28ff

I tried different names, times etc. but when I enter the Client ID, Client Secret and Token and click on generate, this is what I receive:

"An error occurred while deploying components to IBM Cloud Functions. For troubleshooting information, see https://github.com/watson-developer-cloud/conversation-connector/blob/master/README.md#troubleshooting."

Thank you!

**Comment by mitchmason** [comment]
There are a number of things that can happen here...
The most common ones I see are that your Bluemix region is not us-south or Frankfurt (whichever your Watson assistant instance is in) then it will throw an error.
The next most common error I see is that you do not have enough instances left on your lite plan of Bluemix. I believe you only get a few of them for free so you may have too many.
The last most common one is that you already have a lite instance of cloudant, and as part of this deployment process we try to give you another instance of cloudant which throws an error because you cannot have two free plans.

**Comment by DancingCryptos** [comment]
Thank you! What's the solution to the last one? How can I deploy the solution on my own cloudant?

"The last most common one is that you already have a lite instance of cloudant, and as part of this deployment process we try to give you another instance of cloudant which throws an error because you cannot have two free plans."

**Comment by mitchmason** [comment]
You could potentially rename your instance of cloudant to what it needs to be called... I think you'd have to check cloud function logs I think to see what its looking for? I assume that means you already have one instance and dont want to lose it
